### ISSUE TITLE
Include Paths not set correctly

### ISSUE THREAD

**Issue by carterols** [scottaronbloom/vsprojmaker#1]
Each .vcxproj file is pointing to the wrong PropertySheets.props file. For example, the property for the hdloffice .vcxproj was C:\\msys64\\home\\m3nnd8\\dev-2021\\build\\win64\\hdloffice\\main\\src\\PropertySheetIncludes.props instead of C:\\msys64\\home\\m3nnd8\\dev-2021\\build\\win64\\hdloffice\\main\\PropertySheetIncludes.props. It seems as though there was an unintended "src" directory added.

The other thing that caused the include path to not get set correctly was that there was an error in the PropertySheets.props file. For example:

- When trying to point to tcltk in local prod, it used C:/msys64/home/m3nnd8/dev-2021/src/../../../../../../localprod/tcltk/tcl8605-20201227/debug/win64/usr/include, which was non-existent. It should have been C:/localprod/tcltk/tcl8605-20201227/debug/win64/usr/include here.

- Some paths also didn’t have a semicolon separating them. Ex)  C:/msys64/home/m3nnd8/dev-2021/src/C:/localprod/tcltk/tcl8605-20201227/debug/win64/usr/include

**Comment by towel42-com** [comment]
Fixed with the v0.14 tag/release
